package com.livae.ff.app;

import android.support.annotation.DrawableRes;
import android.support.annotation.StringRes;

public class Constants {

	public static final String MARKET_PACKAGE_ID = "com.android.vending";

	public enum COUNTRY {
		AD(R.string.country_ad, R.drawable.flag_ad),
		AE(R.string.country_ae, R.drawable.flag_ae),
		AF(R.string.country_af, R.drawable.flag_af),
		AG(R.string.country_ag, R.drawable.flag_ag),
		AI(R.string.country_ai, R.drawable.flag_ai),
		AL(R.string.country_al, R.drawable.flag_al),
		AM(R.string.country_am, R.drawable.flag_am),
		AO(R.string.country_ao, R.drawable.flag_ao),
		AQ(R.string.country_aq, R.drawable.flag_aq),
		AR(R.string.country_ar, R.drawable.flag_ar),
		AS(R.string.country_as, R.drawable.flag_as),
		AT(R.string.country_at, R.drawable.flag_at),
		AU(R.string.country_au, R.drawable.flag_au),
		AW(R.string.country_aw, R.drawable.flag_aw),
		AX(R.string.country_ax, R.drawable.flag_ax),
		AZ(R.string.country_az, R.drawable.flag_az),
		BA(R.string.country_ba, R.drawable.flag_ba),
		BB(R.string.country_bb, R.drawable.flag_bb),
		BD(R.string.country_bd, R.drawable.flag_bd),
		BE(R.string.country_be, R.drawable.flag_be),
		BF(R.string.country_bf, R.drawable.flag_bf),
		BG(R.string.country_bg, R.drawable.flag_bg),
		BH(R.string.country_bh, R.drawable.flag_bh),
		BI(R.string.country_bi, R.drawable.flag_bi),
		BJ(R.string.country_bj, R.drawable.flag_bj),
		BL(R.string.country_bl, R.drawable.flag_bl),
		BM(R.string.country_bm, R.drawable.flag_bm),
		BN(R.string.country_bn, R.drawable.flag_bn),
		BO(R.string.country_bo, R.drawable.flag_bo),
		BQ(R.string.country_bq/*, R.drawable.flag_bq*/),
		BR(R.string.country_br, R.drawable.flag_br),
		BS(R.string.country_bs, R.drawable.flag_bs),
		BT(R.string.country_bt, R.drawable.flag_bt),
		BV(R.string.country_bv/*, R.drawable.flag_bv*/),
		BW(R.string.country_bw, R.drawable.flag_bw),
		BY(R.string.country_by, R.drawable.flag_by),
		BZ(R.string.country_bz, R.drawable.flag_bz),
		CA(R.string.country_ca, R.drawable.flag_ca),
		CC(R.string.country_cc, R.drawable.flag_cc),
		CD(R.string.country_cd, R.drawable.flag_cd),
		CF(R.string.country_cf, R.drawable.flag_cf),
		CG(R.string.country_cg, R.drawable.flag_cg),
		CH(R.string.country_ch, R.drawable.flag_ch),
		CI(R.string.country_ci, R.drawable.flag_ci),
		CK(R.string.country_ck, R.drawable.flag_ck),
		CL(R.string.country_cl, R.drawable.flag_cl),
		CM(R.string.country_cm, R.drawable.flag_cm),
		CN(R.string.country_cn, R.drawable.flag_cn),
		CO(R.string.country_co, R.drawable.flag_co),
		CR(R.string.country_cr, R.drawable.flag_cr),
		CU(R.string.country_cu, R.drawable.flag_cu),
		CV(R.string.country_cv, R.drawable.flag_cv),
		CW(R.string.country_cw, R.drawable.flag_cw),
		CX(R.string.country_cx, R.drawable.flag_cx),
		CY(R.string.country_cy, R.drawable.flag_cy),
		CZ(R.string.country_cz, R.drawable.flag_cz),
		DE(R.string.country_de, R.drawable.flag_de),
		DJ(R.string.country_dj, R.drawable.flag_dj),
		DK(R.string.country_dk, R.drawable.flag_dk),
		DM(R.string.country_dm, R.drawable.flag_dm),
		DO(R.string.country_do, R.drawable.flag_do),
		DZ(R.string.country_dz, R.drawable.flag_dz),
		EC(R.string.country_ec, R.drawable.flag_ec),
		EE(R.string.country_ee, R.drawable.flag_ee),
		EG(R.string.country_eg, R.drawable.flag_eg),
		EH(R.string.country_eh, R.drawable.flag_eh),
		ER(R.string.country_er, R.drawable.flag_er),
		ES(R.string.country_es, R.drawable.flag_es),
		ET(R.string.country_et, R.drawable.flag_et),
		FI(R.string.country_fi, R.drawable.flag_fi),
		FJ(R.string.country_fj, R.drawable.flag_fj),
		FK(R.string.country_fk, R.drawable.flag_fk),
		FM(R.string.country_fm, R.drawable.flag_fm),
		FO(R.string.country_fo, R.drawable.flag_fo),
		FR(R.string.country_fr, R.drawable.flag_fr),
		GA(R.string.country_ga, R.drawable.flag_ga),
		GB(R.string.country_gb, R.drawable.flag_gb),
		GD(R.string.country_gd, R.drawable.flag_gd),
		GE(R.string.country_ge, R.drawable.flag_ge),
		GF(R.string.country_gf/*, R.drawable.flag_gf*/),
		GG(R.string.country_gg, R.drawable.flag_gg),
		GH(R.string.country_gh, R.drawable.flag_gh),
		GI(R.string.country_gi, R.drawable.flag_gi),
		GL(R.string.country_gl, R.drawable.flag_gl),
		GM(R.string.country_gm, R.drawable.flag_gm),
		GN(R.string.country_gn, R.drawable.flag_gn),
		GP(R.string.country_gp/*, R.drawable.flag_gp*/),
		GQ(R.string.country_gq, R.drawable.flag_gq),
		GR(R.string.country_gr, R.drawable.flag_gr),
		GS(R.string.country_gs, R.drawable.flag_gs),
		GT(R.string.country_gt, R.drawable.flag_gt),
		GU(R.string.country_gu, R.drawable.flag_gu),
		GW(R.string.country_gw, R.drawable.flag_gw),
		GY(R.string.country_gy, R.drawable.flag_gy),
		HK(R.string.country_hk, R.drawable.flag_hk),
		HM(R.string.country_hm/*, R.drawable.flag_hm*/),
		HN(R.string.country_hn, R.drawable.flag_hn),
		HR(R.string.country_hr, R.drawable.flag_hr),
		HT(R.string.country_ht, R.drawable.flag_ht),
		HU(R.string.country_hu, R.drawable.flag_hu),
		ID(R.string.country_id, R.drawable.flag_id),
		IE(R.string.country_ie, R.drawable.flag_ie),
		IL(R.string.country_il, R.drawable.flag_il),
		IM(R.string.country_im, R.drawable.flag_im),
		IN(R.string.country_in, R.drawable.flag_in),
		IO(R.string.country_io/*, R.drawable.flag_io*/),
		IQ(R.string.country_iq, R.drawable.flag_iq),
		IR(R.string.country_ir, R.drawable.flag_ir),
		IS(R.string.country_is, R.drawable.flag_is),
		IT(R.string.country_it, R.drawable.flag_it),
		JE(R.string.country_je, R.drawable.flag_je),
		JM(R.string.country_jm, R.drawable.flag_jm),
		JO(R.string.country_jo, R.drawable.flag_jo),
		JP(R.string.country_jp, R.drawable.flag_jp),
		KE(R.string.country_ke, R.drawable.flag_ke),
		KG(R.string.country_kg, R.drawable.flag_kg),
		KH(R.string.country_kh, R.drawable.flag_kh),
		KI(R.string.country_ki, R.drawable.flag_ki),
		KM(R.string.country_km, R.drawable.flag_km),
		KN(R.string.country_kn, R.drawable.flag_kn),
		KP(R.string.country_kp/*, R.drawable.flag_kp*/),
		KR(R.string.country_kr, R.drawable.flag_kr),
		KW(R.string.country_kw, R.drawable.flag_kw),
		KY(R.string.country_ky, R.drawable.flag_ky),
		KZ(R.string.country_kz, R.drawable.flag_kz),
		LA(R.string.country_la, R.drawable.flag_la),
		LB(R.string.country_lb, R.drawable.flag_lb),
		LC(R.string.country_lc, R.drawable.flag_lc),
		LI(R.string.country_li, R.drawable.flag_li),
		LK(R.string.country_lk, R.drawable.flag_lk),
		LR(R.string.country_lr, R.drawable.flag_lr),
		LS(R.string.country_ls, R.drawable.flag_ls),
		LT(R.string.country_lt, R.drawable.flag_lt),
		LU(R.string.country_lu, R.drawable.flag_lu),
		LV(R.string.country_lv, R.drawable.flag_lv),
		LY(R.string.country_ly, R.drawable.flag_ly),
		MA(R.string.country_ma, R.drawable.flag_ma),
		MC(R.string.country_mc, R.drawable.flag_mc),
		MD(R.string.country_md, R.drawable.flag_md),
		ME(R.string.country_me, R.drawable.flag_me),
		MF(R.string.country_mf, R.drawable.flag_mf),
		MG(R.string.country_mg, R.drawable.flag_mg),
		MH(R.string.country_mh, R.drawable.flag_mh),
		MK(R.string.country_mk, R.drawable.flag_mk),
		ML(R.string.country_ml, R.drawable.flag_ml),
		MM(R.string.country_mm, R.drawable.flag_mm),
		MN(R.string.country_mn, R.drawable.flag_mn),
		MO(R.string.country_mo, R.drawable.flag_mo),
		MP(R.string.country_mp, R.drawable.flag_mp),
		MQ(R.string.country_mq, R.drawable.flag_mq),
		MR(R.string.country_mr, R.drawable.flag_mr),
		MS(R.string.country_ms, R.drawable.flag_ms),
		MT(R.string.country_mt, R.drawable.flag_mt),
		MU(R.string.country_mu, R.drawable.flag_mu),
		MV(R.string.country_mv, R.drawable.flag_mv),
		MW(R.string.country_mw, R.drawable.flag_mw),
		MX(R.string.country_mx, R.drawable.flag_mx),
		MY(R.string.country_my, R.drawable.flag_my),
		MZ(R.string.country_mz, R.drawable.flag_mz),
		NA(R.string.country_na, R.drawable.flag_na),
		NC(R.string.country_nc, R.drawable.flag_nc),
		NE(R.string.country_ne, R.drawable.flag_ne),
		NF(R.string.country_nf, R.drawable.flag_nf),
		NG(R.string.country_ng, R.drawable.flag_ng),
		NI(R.string.country_ni, R.drawable.flag_ni),
		NL(R.string.country_nl, R.drawable.flag_nl),
		NO(R.string.country_no, R.drawable.flag_no),
		NP(R.string.country_np, R.drawable.flag_np),
		NR(R.string.country_nr, R.drawable.flag_nr),
		NU(R.string.country_nu, R.drawable.flag_nu),
		NZ(R.string.country_nz, R.drawable.flag_nz),
		OM(R.string.country_om, R.drawable.flag_om),
		PA(R.string.country_pa, R.drawable.flag_pa),
		PE(R.string.country_pe, R.drawable.flag_pe),
		PF(R.string.country_pf, R.drawable.flag_pf),
		PG(R.string.country_pg, R.drawable.flag_pg),
		PH(R.string.country_ph, R.drawable.flag_ph),
		PK(R.string.country_pk, R.drawable.flag_pk),
		PL(R.string.country_pl, R.drawable.flag_pl),
		PM(R.string.country_pm/*, R.drawable.flag_pm*/),
		PN(R.string.country_pn, R.drawable.flag_pn),
		PR(R.string.country_pr, R.drawable.flag_pr),
		PS(R.string.country_ps, R.drawable.flag_ps),
		PT(R.string.country_pt, R.drawable.flag_pt),
		PW(R.string.country_pw, R.drawable.flag_pw),
		PY(R.string.country_py, R.drawable.flag_py),
		QA(R.string.country_qa, R.drawable.flag_qa),
		RE(R.string.country_re/*, R.drawable.flag_re*/),
		RO(R.string.country_ro, R.drawable.flag_ro),
		RS(R.string.country_rs, R.drawable.flag_rs),
		RU(R.string.country_ru, R.drawable.flag_ru),
		RW(R.string.country_rw, R.drawable.flag_rw),
		SA(R.string.country_sa, R.drawable.flag_sa),
		SB(R.string.country_sb, R.drawable.flag_sb),
		SC(R.string.country_sc, R.drawable.flag_sc),
		SD(R.string.country_sd, R.drawable.flag_sd),
		SE(R.string.country_se, R.drawable.flag_se),
		SG(R.string.country_sg, R.drawable.flag_sg),
		SH(R.string.country_sh, R.drawable.flag_sh),
		SI(R.string.country_si, R.drawable.flag_si),
		SJ(R.string.country_sj/*, R.drawable.flag_sj*/),
		SK(R.string.country_sk, R.drawable.flag_sk),
		SL(R.string.country_sl, R.drawable.flag_sl),
		SM(R.string.country_sm, R.drawable.flag_sm),
		SN(R.string.country_sn, R.drawable.flag_sn),
		SO(R.string.country_so, R.drawable.flag_so),
		SR(R.string.country_sr, R.drawable.flag_sr),
		SS(R.string.country_ss, R.drawable.flag_ss),
		ST(R.string.country_st, R.drawable.flag_st),
		SV(R.string.country_sv, R.drawable.flag_sv),
		SX(R.string.country_sx/*, R.drawable.flag_sx*/),
		SY(R.string.country_sy, R.drawable.flag_sy),
		SZ(R.string.country_sz, R.drawable.flag_sz),
		TC(R.string.country_tc, R.drawable.flag_tc),
		TD(R.string.country_td, R.drawable.flag_td),
		TF(R.string.country_tf, R.drawable.flag_tf),
		TG(R.string.country_tg, R.drawable.flag_tg),
		TH(R.string.country_th, R.drawable.flag_th),
		TJ(R.string.country_tj, R.drawable.flag_tj),
		TK(R.string.country_tk, R.drawable.flag_tk),
		TL(R.string.country_tl/*, R.drawable.flag_tl*/),
		TM(R.string.country_tm, R.drawable.flag_tm),
		TN(R.string.country_tn, R.drawable.flag_tn),
		TO(R.string.country_to, R.drawable.flag_to),
		TR(R.string.country_tr, R.drawable.flag_tr),
		TT(R.string.country_tt, R.drawable.flag_tt),
		TV(R.string.country_tv, R.drawable.flag_tv),
		TW(R.string.country_tw, R.drawable.flag_tw),
		TZ(R.string.country_tz, R.drawable.flag_tz),
		UA(R.string.country_ua, R.drawable.flag_ua),
		UG(R.string.country_ug, R.drawable.flag_ug),
		UM(R.string.country_um/*, R.drawable.flag_um*/),
		US(R.string.country_us, R.drawable.flag_us),
		UY(R.string.country_uy, R.drawable.flag_uy),
		UZ(R.string.country_uz, R.drawable.flag_uz),
		VA(R.string.country_va, R.drawable.flag_va),
		VC(R.string.country_vc, R.drawable.flag_vc),
		VE(R.string.country_ve, R.drawable.flag_ve),
		VG(R.string.country_vg, R.drawable.flag_vg),
		VI(R.string.country_vi, R.drawable.flag_vi),
		VN(R.string.country_vn, R.drawable.flag_vn),
		VU(R.string.country_vu, R.drawable.flag_vu),
		WF(R.string.country_wf, R.drawable.flag_wf),
		WS(R.string.country_ws, R.drawable.flag_ws),
		YE(R.string.country_ye, R.drawable.flag_ye),
		YT(R.string.country_yt, R.drawable.flag_yt),
		ZA(R.string.country_za, R.drawable.flag_za),
		ZM(R.string.country_zm, R.drawable.flag_zm),
		ZW(R.string.country_zw, R.drawable.flag_zw);

		private final int countryStringResId;

		private final int countryFlagResId;

		private COUNTRY(@StringRes int countryStringResId) {
			this(countryStringResId, 0);
		}

		private COUNTRY(@StringRes int countryStringResId, @DrawableRes int countryFlagResId) {
			this.countryStringResId = countryStringResId;
			this.countryFlagResId = countryFlagResId;
		}

		public int getCountryStringResId() {
			return countryStringResId;
		}

		public int getCountryFlagResId() {
			return countryFlagResId;
		}

	}

}
